services:
  spamassassin:
    image: instantlinux/spamassassin:4.0.0-6
    platform: linux/x86_64
    ports:
      - ${SPAMASSASSIN_PORT:-783}:783
    restart: always

  redis:
    image: "redis/redis-stack:7.2.0-v8"
    restart: always
    ports:
      - ${REDIS_PORT:-6379}:6379
      - ${REDIS_INSIGHT_PORT:-8001}:8001
    volumes:
      - redis-data:/data

  eml_analyzer:
    build:
      context: ./
      dockerfile: app.Dockerfile
      args:
        VITE_CLERK_PUBLISHABLE_KEY: ${VITE_CLERK_PUBLISHABLE_KEY}
    ports:
      - ${PORT:-8050}:8050
    environment:
      - PORT=8050
      - SPAMASSASSIN_HOST=spamassassin
      - SPAMASSASSIN_PORT=${SPAMASSASSIN_PORT:-783}
      - REDIS_URL=redis://redis:${REDIS_PORT:-6379}
      - VIRUSTOTAL_API_KEY=${VIRUSTOTAL_API_KEY}
      - URLSCAN_API_KEY=${URLSCAN_API_KEY}
      - EMAIL_REP_API_KEY=${EMAIL_REP_API_KEY}
      - IPQUALITYSCORE_API_KEY=${IPQUALITYSCORE_API_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
    restart: always
    depends_on:
      - spamassassin
      - redis

volumes:
  redis-data:
